### ISSUE TITLE
keepsorted breaks multi-line arrays

### ISSUE THREAD

**Issue by rmvermeulen** [maksym-arutyunyan/keepsorted#34]
Hi! Thanks for making this!

I just ran into this issue. I had a quick try at patching it but it seems to need some more thought put into it.
I'm currently just using `keepsorted: ignore block`.

For example:
```toml
[dependencies.bevy]
workspace = true
features = [
  # lots of features here
]
```
turns into 
```toml
[dependencies.bevy]
  # lots of features here
]
features = [
workspace = true
```
Which is invalid of course.

Current workaround/solution:
```toml
[dependencies.bevy]
workspace = true
# keepsorted: ignore block
features = [
  # lots of features here
]
```
